#pragma once
#include <iostream>
#include <cstring>
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <fcntl.h>
#include <cstdlib>
#include <vector>
#include <poll.h>
#include <string>
#include <ostream>
#include <list>
#include <map>
#include <sstream>
